name: test_view
description: A sample Polymer application
dependencies:
  hexacore:
    path: ../hexacore
  hexacore_view:
    path: ../hexacore_view
  polymer: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points: web/test_view.html
